### ISSUE TITLE
[Bug]: use `pyinstaller` build windows exe will crash when running with following error

### ISSUE THREAD

**Issue by xiaosongfu** [thewebscraping/tls-requests#13]
### TLS Requests version

v1.0.9

### Issue description

```
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admi\\AppData\\Local\\Temp\\_MEI320122\\tls_requests\\models\\libraries.pyc'
```

### Steps to reproduce / Code Sample

cli.spec

```
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['cli.py'],
    pathex=[],
    binaries=[],
    datas=[("res", ".")],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cli',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="res/logo.ico"
)
```

build command:

```
pyinstaller cli.spec
```

**Comment by thewebscraping** [comment]
@xiaosongfu 
Are you want build to local?

**Comment by xiaosongfu** [comment]
> @xiaosongfu Are you want build to local?

no, I want to build on my local windows pc, but running on other windows pc

**Comment by xiaosongfu** [comment]
> @xiaosongfu Are you want build to local?

I want to build an EXE executable file, and send it to my friends, they will execute it

**Comment by thewebscraping** [comment]
@xiaosongfu 
Please use pip for install. Read docs: [https://thewebscraping.github.io/tls-requests/](https://thewebscraping.github.io/tls-requests/)

**Comment by xiaosongfu** [comment]
> @xiaosongfu Please use pip for install. Read docs: https://thewebscraping.github.io/tls-requests/

my friends's pc has no pip

**Comment by thewebscraping** [comment]
@xiaosongfu 
Sorry, I can't help you with this case. You can refer to origin repo: https://github.com/bogdanfinn/tls-client

**Comment by thewebscraping** [comment]
`cli` is not support yet
