### ISSUE TITLE
[Bug]: AsyncClient is not asynchronous

### ISSUE THREAD

**Issue by yassinemab** [thewebscraping/tls-requests#15]
### TLS Requests version

1.0.9

### Issue description

It seems like the AsyncClient has not been implemented correctly. Looking at the `send` function in the `AsyncClient` class in the `client.py` file, i can see that the synchronous function `_send()` is called. This causes blocking and doesnt allow me to run the client asynchronously. Am i doing something wrong or does this need to be fixed?

### Steps to reproduce / Code Sample

-

**Comment by thewebscraping** [comment]
Hi @yassinemab 
You are right, I use the same ._send method for AsyncClient and SyncClient. Can you share the error log, the system you are currently using and the code to use AsyncClient? I will try to fix it tomorrow.

Thanks

**Comment by thewebscraping** [comment]
Hi @yassinemab
Please install new releases

```shell
pip install -q -U wrapper-tls-requests
```
