### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by nmaisonneuve** [thewebscraping/tls-requests#8]
Hi. How to add proxy support with tls_requests ?  I did not find any example.
thanks !

**Comment by thewebscraping** [comment]
@nmaisonneuve
Yes, it's support.
I will fix tomorrow for new release.

**Comment by thewebscraping** [comment]
Hi @nmaisonneuve 
Bug is fixed, please reinstall new:

```python
pip install wrapper-tls-requests==1.0.7
```

**Example Usage:**

```python
import tls_requests
proxy = ' http://127.0.0.1:8080'  # http://user:pass@127.0.0.1:8080'
r = tls_requests.get('https://httpbin.org/get', proxy=proxy) 
```

For the next release, we will support a proxy pool, including:
- Rotating Proxies: accept multiple proxies and support rotating proxies.
- Smart Proxy Route: bypass domain feature to save bandwidth when using Residential Proxies.
